#include "sPhenixStyle.h"
#include "sPhenixStyle.C"
#include <string>

int PlottingMactor_GQRatio(TFile* f, std::string trig)
{
SetsPhenixStyle();
TH1F* evts1=(TH1F*)f->Get("event");
int a=evts1->GetEntries();
int b=log10(a);
std::string evts="10^{"+std::to_string(b)+"} events";
TH1F* e2c=(TH1F*)f->Get("e2c");
TH1F* e3c=(TH1F*)f->Get("e3c");
TH1F* e2c_g=(TH1F*)f->Get("e2c_g");
TH1F* e3c_g=(TH1F*)f->Get("e3c_g");
TH1F* e2c_q=(TH1F*)f->Get("e2c_q");
TH1F* e3c_q=(TH1F*)f->Get("e3c_q");
TCanvas* c1=new TCanvas();
TPad* p1=new TPad("p1", "p1", 0, 0.35, 1, 1);
TPad* p2=new TPad("p2", "p2", 0, 0, 1, 0.33);
p1->cd();
e2c->GetXaxis()->SetRangeUser(0, 1);
e2c->Scale(1/e2c->GetBinWidth(10));
e2c->SetYTitle("#frac{d E2C}{d R_{L}}");
e2c->GetYaxis()->SetRangeUser(0, 1.33*e2c->GetMaximum());
e2c->Draw();
e2c_g->SetLineColor(kPink+1);
e2c_g->SetMarkerColor(kPink+1);
e2c_q->SetLineColor(7);
e2c_q->SetMarkerColor(7);
e2c_g->Scale(1/e2c_g->GetBinWidth(10));
e2c_q->Scale(1/e2c_q->GetBinWidth(10));
e2c_g->Draw("same");
e2c_q->Draw("same");
TLegend* l=new TLegend(0.1, 0.8, 0.5, 1);
l->AddEntry("", "#bf{#it{sPHENIX}} Internal", "");
l->AddEntry("", Form("#bf{Herwig} 2 #rightarrow 2 with %s trigger, %s events", trig.c_str(), evts.c_str()), "");
l->AddEntry("", "Jets Identified from final state particles of the initiating parton", "");
l->SetFillStyle(0);
l->SetFillColor(0);
l->SetBorderSize(0);
TLegend* l1=new TLegend(0.5, 0.15, 1, 0.35);
l1->SetTextSize(0.03f);
l1->AddEntry(e2c, "All Jets, scaled by N_{jets}");
l1->AddEntry(e2c_g, "Gluon initiated jets, scaled over N_{jets}");
l1->AddEntry(e2c_q, "Quark initiated jets, scaled over N_{jets}");
l1->SetFillStyle(0);
l1->SetFillColor(0);
l1->SetBorderSize(0);
l->Draw(); 
l1->Draw();
c1->cd();
p1->Draw();
p2->cd();
TH1F* hg=(TH1F*)e2c_g->Clone();
TH1F* hq=(TH1F*)e2c_q->Clone();
hg->Divide(hq); 
hg->SetYTitle("Gluon/Quark Jet");
hg->SetLineColor(kRed);
hg->SetMarkerColor(kRed);
hg->GetXaxis()->SetRangeUser(0, 1);
hg->Draw(); 
c1->cd();
p2->Draw();
TCanvas* c2=new TCanvas();
TPad* p12=new TPad("p12", "p1", 0, 0.35, 1, 1);
TPad* p22=new TPad("p22", "p2", 0, 0, 1, 0.33);
p12->cd();
e3c->GetXaxis()->SetRangeUser(0, 1);
e3c->Scale(1/e3c->GetBinWidth(10));
e3c->GetYaxis()->SetTitle("#frac{d E3C}{d R_{L}}");
e3c->Draw();
e3c->GetYaxis()->SetRangeUser(0, 1.33*e3c->GetMaximum());
e3c_g->SetLineColor(kPink+1);
e3c_g->SetMarkerColor(kPink+1);
e3c_q->SetLineColor(7);
e3c_q->SetMarkerColor(7);
e3c_g->Scale(1/e3c_g->GetBinWidth(10));
e3c_q->Scale(1/e3c_q->GetBinWidth(10));
e3c_g->Draw("same");
e3c_q->Draw("same");
TLegend* l3=new TLegend(0.05, 0.8, 0.5, 1);
l3->AddEntry("", "#bf{#it{sPHENIX}} Internal", "");
l3->AddEntry("", Form("#bf{Herwig} 2 #rightarrow 2 with %s trigger, %s events", trig.c_str(), evts.c_str()), "");
l3->AddEntry("", "Jets Identified from final state particles of the initiating parton", "");
l3->SetFillStyle(0);
l3->SetFillColor(0);
l3->SetBorderSize(0);
TLegend* l4=new TLegend(0.45, 0.15, 0.7, 0.35);
l4->SetTextSize(0.03f);
l4->SetFillStyle(0);
l4->SetFillColor(0);
l4->SetBorderSize(0);
l4->AddEntry(e2c, "All Jets, scaled by N_{jets}");
l4->AddEntry(e2c_g, "Gluon initiated jets, scaled over N_{jets}");
l4->AddEntry(e2c_q, "Quark initiated jets, scaled over N_{jets}");
l3->Draw(); 
l4->Draw();
c2->cd();
p12->Draw();
p22->cd();
TH1F* hg1=(TH1F*)e3c_g->Clone();
TH1F* hq1=(TH1F*)e3c_q->Clone();
hg1->Divide(hq1); 
hg1->SetYTitle("Gluon/Quark Jet");
hg1->GetXaxis()->SetRangeUser(0, 1);
hg1->GetYaxis()->SetRangeUser(0, 2);
hg1->SetLineColor(kRed);
hg1->SetMarkerColor(kRed);
hg1->Draw(); 
c2->cd();
p22->Draw();
c1->Print(Form("~/e2c_qg_disc_%s.pdf", trig.c_str()));
c2->Print(Form("~/e3c_qg_disc_%s.pdf", trig.c_str()));
return 1;
}
